<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractDevice extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'devices';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'serialNum' => 'string',
        'brandName' => 'string',
        'model' => 'string',
        'purchaseDate' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}
